pili/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
    ValidationError,
)
from wtforms.validators import DataRequired, Email, Length, Regexp

from pili.models import Role, User


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')


class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')


class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(1, 64),
            Regexp(
                '^[A-Za-z][A-Za-z0-9_.]*$',
                0,
                'Usernames must have only letters, ' 'numbers, dots or underscores',
            ),
        ],
    )
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [
            (role.id, role.name) for role in Role.query.order_by(Role.name).all()
        ]
        self.user = user

    def validate_email(self, field):
        if (
            field.data != self.user.email
            and User.query.filter_by(email=field.data).first()
        ):
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if (
            field.data != self.user.username
            and User.query.filter_by(username=field.data).first()
        ):
            raise ValidationError('Username already in use.')


class CommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

pili/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from pili.main import views, errors
from pili.models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

pili/main/views.py
from flask import (
    abort,
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_sqlalchemy import get_debug_queries

from pili.app import db
from pili.ctrl.forms import CsrfTokenForm
from pili.decorators import permission_required
from pili.main import main
from pili.main.forms import CommentForm
from pili.models import (
    Category,
    Comment,
    Like,
    Message,
    MessageAck,
    Permission,
    Post,
    Tag,
    User,
)


@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    tags = Tag.query.all()
    categories = Category.query.all()
    return render_template(
        'main/index.html',
        posts=posts,
        tags=tags,
        categories=categories,
        show_followed=show_followed,
        pagination=pagination,
    )


@main.route('/tag/<alias>')
def tag(alias):
    tag = Tag.query.filter_by(alias=alias).first_or_404()
    page = request.args.get('page', 1, type=int)

    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts.filter(Post.tags.contains(tag))
    else:
        query = tag.posts
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/tag.html',
        tag=tag,
        posts=posts,
        show_followed=show_followed,
        pagination=pagination,
    )


@main.route('/user/<username>/profile')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/user.html', user=user, posts=posts, pagination=pagination
    )


@main.route('/<category>/<int:id>/<alias>', methods=['GET', 'POST'])
@main.route(
    '/<category>/<int:id>/<alias>/reply/<int:parent_id>', methods=['GET', 'POST']
)
def post(category, id, alias, parent_id=None):
    # https://stackoverflow.com/questions/17873820/flask-url-for-with-multiple-parameters
    post = Post.query.get_or_404(id)
    form = CommentForm()
    recipient = None
    if parent_id:
        parent_comment = Comment.query.get_or_404(parent_id)
        recipient = parent_comment.author
        # parent comment should be under the current post
        if parent_comment.post_id != id:
            flash('Operation is not permitted.', 'warning')
            return redirect(
                url_for(
                    'main.post',
                    category=post.category.alias,
                    id=post.id,
                    alias=post.alias,
                    page=-1,
                )
            )
    if form.validate_on_submit():
        screened = current_app.config['PILI_COMMENTS_SCREENING']
        comment = Comment(
            body=form.body.data,
            parent_id=parent_id,
            post=post,
            screened=screened,
            author=current_user._get_current_object(),
            recipient=recipient,
        )
        db.session.add(comment)
        """
        # comment form prepopulated through Reply
        if parent_id:
            ## http://stackoverflow.com/a/5083472/4241180 ##
            # to get auto-incremented primary key for the comment,
            # one needs to flush session first and then use comment.id
            db.session.flush()
            reply = Reply(id=comment.id,
                          parent_id=parent_id, \
                          replier=current_user._get_current_object(), \
                          repliee=repliee)
            db.session.add(reply)
        """

        flash('Your comment has been published.', 'success')
        return redirect(
            url_for(
                'main.post',
                category=post.category.id,
                id=post.id,
                alias=post.alias,
                page=-1,
            )
        )
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) // current_app.config[
            'PILI_COMMENTS_PER_PAGE'
        ] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['PILI_COMMENTS_PER_PAGE'], error_out=False
    )
    comments = pagination.items
    # if it's a reply, then prepopulate the form
    if parent_id:
        form.body.data = parent_comment.author.username + ', '
    return render_template(
        'main/post.html',
        posts=[post],
        form=form,
        comments=comments,
        pagination=pagination,
    )


# # TODO: rewrite as API function
# @main.route('/like', methods=['POST'])
# @login_required
# @permission_required(Permission.FOLLOW)
# def like_item():
#     try:
#         post_id = request.json.get('post_id', None)
#         comment_id = request.json.get('comment_id', None)
#         user_id = request.json.get('user_id', None)
#         action = request.json.get('action', None)
#         csrf = request.json.get('csrf', None)
#     except (KeyError, TypeError):
#         return jsonify(
#             {
#                 'status': 'error',
#                 'message': 'Function takes four parameters: '
#                 'post or commend id; user id; action type; csrf token',
#             }
#         )


@main.route('/likes/post/<int:id>/like')
@login_required
@permission_required(Permission.FOLLOW)
def like_post(id):
    post = Post.query.get_or_404(id)
    like = Like(post=post, user=current_user)
    db.session.add(like)
    return redirect(
        url_for('main.post', category=post.category.alias, id=post.id, alias=post.alias)
    )


@main.route('/likes/post/<int:id>/unlike')
@login_required
@permission_required(Permission.FOLLOW)
def unlike_post(id):
    post = Post.query.get_or_404(id)
    like = Like.query.filter(
        (Like.user == current_user) & (Like.post == post)
    ).first_or_404()
    db.session.delete(like)
    return redirect(
        url_for('main.post', category=post.category.alias, id=post.id, alias=post.alias)
    )


@main.route('/likes/comment/<int:id>/like')
@login_required
@permission_required(Permission.FOLLOW)
def like_comment(id):
    comment = Comment.query.get_or_404(id)
    like = Like(comment=comment, user=current_user)
    db.session.add(like)
    return redirect(
        url_for(
            'main.post',
            category=comment.post.category.alias,
            id=comment.post.id,
            alias=comment.post.alias,
            page=request.args.get('page', 1, type=int),
            _anchor='comment{0}'.format(id),
        )
    )


@main.route('/likes/comment/<int:id>/unlike')
@login_required
@permission_required(Permission.FOLLOW)
def unlike_comment(id):
    comment = Comment.query.get_or_404(id)
    like = Like.query.filter(
        (Like.user == current_user) & (Like.comment == comment)
    ).first_or_404()
    db.session.delete(like)
    return redirect(
        url_for(
            'main.post',
            category=comment.post.category.alias,
            id=comment.post.id,
            alias=comment.post.alias,
            page=request.args.get('page', 1, type=int),
            _anchor='comment{0}'.format(id),
        )
    )


@main.route('/replies-to/bulk', methods=['POST'])
@login_required
def replies_bulk():
    def replies_action(comments, action):
        msg = {'read': 'marked as read', 'unread': 'marked as not read'}
        message = ''
        fail = ''
        count = 0
        for id in comments:
            comment = Comment.query.get_or_404(id)
            if current_user._get_current_object() == comment.recipient:
                if action == 'read':
                    comment.read = True
                elif action == 'unread':
                    comment.read = False
                # add more actions here
                db.session.add(comment)
                message += str(id) + ', '
                count += 1
            else:
                fail += str(id) + ', '
        message = message.rstrip(', ')
        fail = fail.rstrip(', ')
        status = 'success'
        if message:
            message = 'Comments: {message} have been {action}.'.format(
                message=message, action=msg[action]
            )
        if fail:
            fail = 'Comments: {fail} failed. You are not a recipient of them.'.format(
                fail=fail, action=msg[action]
            )
            status = 'warning'
        return "{message} {fail}".format(message=message, fail=fail), status

    try:
        csrf = request.json['csrf']  # noqa: F841
        comments = list(map(lambda x: int(x), request.json['comments']))
        action = request.json['action']
    except (KeyError, TypeError):
        return jsonify(
            {
                'status': 'error',
                'message': 'Function takes three parameters: '
                'list of comments to be processed; csrf token; action',
            }
        )
    message, status = replies_action(comments, action)
    return jsonify({'status': status, 'message': message})


@main.route('/replies-to/unread/<int:id>')
@login_required
def reply_mark_unread(id):

pili/templates/main/_categories.html
<ul class="list-unstyled categories">
  {% for category in categories %}
  <li class="cateogry">
    <a href="{{ url_for('main.category', alias=category.alias) }}">{{ category.title }}</a> <span class="badge">{{ category.posts.count() }}</span></a>
  </li>
  {% endfor %}
</ul>

pili/templates/main/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            <li{% if p == pagination.page %} class="active"{% endif %}>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

pili/templates/main/_notifications.html
{% if recipient and not single %}
<div class="comment-control">
	<input name="checkbox_select_all" id="select_all" type="checkbox" value=""></span>
	<button class="btn btn-default btn-sm on-check" data-action="read"><span class="glyphicon glyphicon-eye-open" aria-label="Mark as read" title="Mark selected messages as read"></span></button>
        <button class="btn btn-default btn-sm on-check" data-action="unread"><span class="glyphicon glyphicon-eye-close" aria-label="Mark as not read" title="Mark selected messages as not read"></span></button>
	<button class="btn btn-danger btn-sm on-check" data-action="remove"><span class="glyphicon glyphicon-trash" aria-label="Remove selected" title="Remove selected messages"></span></button>

</div>
{% endif %}

<ul class="ctrl-list">
  {% for ack in messages %}
    <li id="message{{ ack.message.id }}" class="ctrl-item {% if not ack.read %}unread{% endif%}">
        <div class="ctrl-item-thumbnail">
            <a href="{{ url_for('.user', username=ack.message.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ ack.message.author.gravatar(size=40) }}">
            </a>
        </div>

	{% if recipient and not single %}
	<div class="ctrl-item-checkbox">
	  <input name="checkbox{{ ack.id }}" id="checkbox{{ ack.id }}" class="ctrl-item-select" type="checkbox" value="{{ ack.id }}">
	</div>
	{% endif %}

	
        <div class="ctrl-item-content">
            <div class="ctrl-item-date">{{ moment(ack.message.timestamp).fromNow() }}</div>
            <div class="ctrl-item-author">
	      <a href="{{ url_for('main.notification', username=ack.recipient.username, id=ack.id) }}">
		{{ ack.message.title }}
	      </a>
	      by
	      <a href="{{ url_for('.user', username=ack.message.author.username) }}">
		{{ ack.message.author.username }}
	      </a>
	    </div>

            <div class="ctrl-item-body">
                {% if ack.message.body_html %}
                  {{ ack.message.body_html | safe }}
                {% else %}
                  {{ ack.message.body }}
                {% endif %}
            </div>

	    {% if recipient %}
 	    {% if ack.read == True %}
	    <button class="btn btn-primary btn-xs on-click" type="button" title="Mark message as read" data-action="unread" data-item-id="{{ ack.id }}"><span class="glyphicon glyphicon-eye-close" aria-label="Unread"></span></button>
	    {% else %}
	    <button class="btn btn-default btn-xs on-click" type="button" title="Mark message as read" data-action="read" data-item-id="{{ ack.id }}"><span class="glyphicon glyphicon-eye-open" aria-label="Read"></span></button>
	    {% endif %}

	      {% if single %}
	      <a href="{{ url_for('main.remove_notification', username=user.username, id=ack.id) }}" class="btn btn-danger btn-xs" role="button" title="Remove message"><span class="glyphicon glyphicon-trash" aria-label="Remove"></span></a>
	      {% else %}
	      <button class="btn btn-danger btn-xs on-click" type="button" title="Remove message" data-action="remove" data-item-id="{{ ack.id }}"><span class="glyphicon glyphicon-trash" aria-label="Remove"></span></button>
	      {% endif %}
	    {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

pili/templates/main/_posts.html
<ul class="posts">
  {% for post in posts %}
  <li class="post">
    <div class="post-thumbnail">
      <a href="{{ url_for('main.user', username=post.author.username) }}">
        <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
      </a>
    </div>
    <div class="post-content">
      <div class="post-data">
	by
	<span class="glyphicon glyphicon-user"></span>
	<a href="{{ url_for('main.user', username=post.author.username) }}">
	  {{ post.author.username }}
	</a>
	{{ moment(post.timestamp).fromNow() }}

	{% if post.category %}
	under
	<a href="{{ url_for('main.category', alias=post.category.alias) }}">
	  <span class="label label-success">{{ post.category.title }}</span>
	</a> category
	{% endif %}

  	  {% if post.tags.count() %}
	  with <span class="glyphicon glyphicon-tag"></span>
	  {% for tag in post.tags %}
	  <a href="{{ url_for('main.tag', alias=tag.alias) }}">
	    {{ tag.title }}
	  </a>
	  {% if not loop.last %},{% endif %}
	  {% endfor %}
	{% endif %}

      </div>
      <div class="post-title">
	<a href="{{ url_for('main.post', category=post.category.alias, id=post.id, alias=post.alias) }}">
	  <h4>{{ post.title }}</h4>
	</a>
      </div>
      <div class="post-author">
      </div>
      <div class="post-body">
        {% if post.body_html %}
        {{ post.body_html | safe }}
        {% else %}
        {{ post.body }}
        {% endif %}
      </div>

      <div class="post-footer">
        {% if current_user == post.author %}
        <a href="{{ url_for('ctrl.edit_post', id=post.id, alias=post.alias) }}"
        class="btn btn-default btn-xs">Edit</a>

        {% elif current_user.has_role('Administrator') or
	current_user.has_role('Editor')  %}
        <a href="{{ url_for('ctrl.edit_post', id=post.id, alias=post.alias) }}"
        class="btn btn-danger btn-xs">Edit [Admin]</a>
        {% endif %}

        {% set post_likes = post.likes.count() %}

        {% if current_user.is_authenticated %}
            {% set post_liked_by_current_user = post.likes.filter_by(user_id=current_user.id).count() %}
        {% else %}
           {% set post_liked_by_current_user = False %}
        {% endif %}

          <a href="{% if not post_liked_by_current_user %}
          {{ url_for('main.like_post', id=post.id) }}
          {% else %}
          {{ url_for('main.unlike_post', id=post.id) }}
          {% endif %}"
          class="btn btn-info btn-xs">
              {% if not post_liked_by_current_user %}
                  <span class="glyphicon glyphicon-heart-empty" aria-hidden="true" title="Not liked by you yet. Click to like"></span>
                  {% else %}
                  <span class="glyphicon glyphicon-heart" aria-hidden="true" title="Liked by you. Click to unlike"></span>
              {% endif %}
              {{ post_likes }} Like{{ post_likes|pluralize("", "s") }}
          </a>

	{% if post.commenting %}
        <a href="{{ url_for('main.post', category=post.category.alias, id=post.id, alias=post.alias) }}#comments"
        class="btn btn-primary btn-xs">{{ post.comments.count() }} Comments</a>
	{% endif %}

      </div>
    </div>
  </li>
  {% endfor %}
</ul>

pili/templates/main/_tags.html
<ul class="list-unstyled tags">
  {% for tag in tags %}
  <li class="tag">
    <a href="{{ url_for('main.tag', alias=tag.alias) }}">{{ tag.title }}</a> <span class="badge">{{ tag.posts.count() }}</span></a>
  </li>
  {% endfor %}
</ul>

pili/templates/main/category.html
{% extends "main/base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}Posts under {{ category.title }}{{ super() }}{% endblock %}

{% set desc = "Posts under {0} category".format(category.title) %}
{% set author = config['PILI_APP_AUTHOR'] %}
{% block meta_opengraph %}
  <meta property="og:type" content="article">
  <meta property="og:title" content="{{ category.title }}">
  <meta property="og:description" content="{{ desc }}">
  <meta property="og:author" content="{{ author }}">
  {% if category.image.filename %}
  {% set img_path = url_for('static', filename='uploads/', _external=True) + category.image.filename %}
  <meta property="og:image" content="{{ img_path }}">
  {% endif %}
{% endblock %}
{% block meta_html %}
  <meta name="author" content="{{ author }}">
  <meta name="description" content="{{ desc }}">
{% endblock %}

{% block page_content %}

<h3>Posts under category {{ category.title }}</h3>


<section class="content">
  <div class="row">
    <div class="col-md-9">
      <section class="post-tabs">
	<ul class="nav nav-tabs">
	  <li{% if not show_followed %} class="active"{% endif %}>
	    <a href="{{ url_for('main.show_all', page='category', alias=category.alias) }}">All</a>
	  </li>
	  {% if current_user.is_authenticated %}
	  <li{% if show_followed %} class="active"{% endif %}>
	    <a href="{{ url_for('main.show_followed', page='category', alias=category.alias) }}">Followers</a>
	  </li>
	  {% endif %}
	</ul>
	{% include 'main/_posts.html' %}
      </section>
      {% if pagination %}
      <div class="pagination">
	{{ macros.pagination_widget(pagination, 'main.category', alias=category.alias) }}
      </div>
      {% endif %}
    </div><!-- col-md-9 -->

    <div class="col-md-3">
      <section class="category">

	  <div class="category-image">
          {% if category.image %}
	        <img class="img-responsive" src="{{ category.image.filename | thumbnail('100x100', crop='fit', quality=75) }}"
		    title="{{ category.image.filename }}" alt="{{ category.image.filename }}">
          {% else %}
          <span class="glyphicon glyphicon-minus" aria-label="None" title="No Image"></span>
          {% endif %}
	  </div>
	  <div class="category-body">
	    {% if category.body_html %}
	    {{ category.body_html | safe }}
	    {% else %}
	    {{ category.body }}
	    {% endif %}
	  </div>
	
      </section>
      
    </div><!-- col-md-3 -->
  </div>
</section>


{% endblock %}

pili/templates/main/comments.html
{% extends "main/base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}Comments by {{ user.username }}{{ super() }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Comments by {{ user.username }}</h1>
</div>
{% set expand = True %}
{% set moderate = True %}
{% set reply = True %}
{% include 'main/_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.comments', username=user.username) }}
</div>
{% endif %}

{% endblock %}

pili/templates/main/followers.html
{% extends "main/base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}{{ title }} {{ user.username }} {{ super() }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>User</th><th>Since</th></tr></thead>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.gravatar(size=32) }}">
		{{ follow.user.name if follow.user.name != None else follow.user.username }}
            </a>
        </td>
        <td>{{ moment(follow.timestamp).format('L') }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, username = user.username) }}
</div>
{% endblock %}

pili/templates/main/replies.html
{% set page = 'user' %}
{% set subpage = 'replies' %}

{% extends "main/base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}Replies to {{ user.username }}{{ super() }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Replies to {{ user.username }}</h1>
</div>
{% set expand = True %}
{% set moderate = True %}
{% set reply = True %}
{% if current_user.is_authenticated and user == current_user %}
  {% set recipient = True %}
{% endif %}

{% include 'main/_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'main.replies', username=user.username) }}
</div>
{% endif %}

<form method="post">
    {{ csrf_form.csrf_token(id="csrf-removal") }}
    {{ csrf_form.id }}
</form>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
 // event handler for select all checkbox
 $('#select_all').change(function() {
     var select_all = $( this );
     if ( select_all.prop('checked') ) {
	 $('.ctrl-item-select').prop('checked', $(this).prop('checked'));
     }
     else if ( select_all.not(':checked') ) {
	 $('.ctrl-item-select').removeAttr('checked');
     }
 })//.change();
</script>

<script>
 // at least one checkbox is checked
 $('input').change(function() {
     if ($(':checked').length > 0) {
	 $('.on-check').show();
     }
     else {
	 $('.on-check').hide();
     }
 })
</script>

<script>
 // POST request
 $('.on-check, .remove').click(function() {
     var button = $( this );
     var comments = [];
     
     if (button.hasClass('remove')) {
	 comments[0] = button.data('id-removal');
     }
     else {
	 $('.ctrl-item-select:checked').each(function(i){
             comments[i] = $(this).val();
	 });
     }
     
     var data = {
	 csrf: $('#csrf-removal').val(),
	 comments: comments,
	 action: button.data('action')
     };

     $.ajaxSetup({
	 beforeSend: function(xhr, settings) {
             if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
		 xhr.setRequestHeader("X-CSRFToken", data['csrf'])
             }
	 }
     });
     
     var remove = confirm('Are you sure?');
     if (remove == true) {
	 $.when( $.ajax({
             url: "{{ url_for('main.replies_bulk', _external=True) }}",
             type: 'post',
             dataType: 'json',
             contentType: 'application/json;charset=UTF-8',
	     accepts: {
		 json: 'application/json',
             },
	     data: JSON.stringify(data),
	     success: function(response) {
		 // message to user
		 var flash = "<div class='alert alert-" + response['status'] + "'>" +
	     		     "<button type='button' class='close' data-dismiss='alert'>&times;</button>" +
	     		     response['message'] + "</div>";
		 // save message to localStorage
		 window.onbeforeunload = function() {
		     localStorage.setItem('message', flash);
		 }
	     },
             error: function(jqXHR, textStatus, errorThrown) {
		 console.log('Error code: ' + jqXHR.status);
		 console.log('Error status: ' + textStatus);
		 console.log('Error thrown: ' + errorThrown);
             }
	 }).done(function(){
	     location.reload();           // reload the page
	     $('html,body').scrollTop(0); // jump on top
	 }));
     };
 })
</script>

<script>
 $( document ).ready(function() {
     var message = localStorage.getItem('message');
     if (message !== null) {
	 $('.page-header').before(message);
     }
     localStorage.removeItem('message');
 });
</script>

{% endblock %}