pili/ctrl/forms.py
from flask_pagedown.fields import PageDownField
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms import (
    BooleanField,
    DateTimeField,
    HiddenField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
    ValidationError,
)
from wtforms.validators import DataRequired, Email, Length, Regexp

from pili.filters import file_exists
from pili.models import Category, Role, User


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')


class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')


class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    username = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(1, 64),
            Regexp(
                '^[A-Za-z][A-Za-z0-9_.]*$',
                0,
                'Usernames must have only letters, ' 'numbers, dots or underscores',
            ),
        ],
    )
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [
            (role.id, role.name) for role in Role.query.order_by(Role.name).all()
        ]
        self.user = user

    def validate_email(self, field):
        if (
            field.data != self.user.email
            and User.query.filter_by(email=field.data).first()
        ):
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if (
            field.data != self.user.username
            and User.query.filter_by(username=field.data).first()
        ):
            raise ValidationError('Username already in use.')


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(1, 128)])
    alias = StringField(
        "URL alias",
        validators=[
            DataRequired(),
            Length(1, 128),
            Regexp(
                r'^(\w|-)+$',
                0,
                'Alias must contain only lowercase ' 'letters and dashes',
            ),
        ],
    )
    description = StringField(
        "Description", validators=[DataRequired(), Length(1, 160)]
    )
    timestamp = DateTimeField("Date and time", format='%Y-%m-%d %H:%M:%S')
    body = PageDownField("Text", validators=[DataRequired()])
    image = StringField("Image", validators=[Length(0, 64)])
    tags = StringField("Tags", validators=[Length(0, 64)])
    featured = BooleanField('Featured')
    commenting = BooleanField('Commenting', default="checked")
    category = SelectField("Category", coerce=int)
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [
            (category.id, category.title)
            for category in Category.query.order_by(Category.timestamp.desc()).all()
        ]


class EditCategoryForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(1, 128)])
    alias = StringField(
        "URL alias",
        validators=[
            DataRequired(),
            Length(1, 128),
            Regexp(
                r'^(\w|-)+$',
                0,
                'Alias must contain only lowercase ' 'letters and dashes',
            ),
        ],
    )
    description = StringField(
        "Description", validators=[DataRequired(), Length(1, 160)]
    )
    body = PageDownField("Text", validators=[DataRequired()])
    image = StringField("Image", validators=[Length(0, 64)])
    timestamp = DateTimeField("Date and time", format='%Y-%m-%d %H:%M:%S')
    featured = BooleanField('Featured')
    submit = SubmitField('Submit')

    # TODO: fix image field in the form. Exceptions do not show up
    # def validate_image(self, field):
    #    if not field.data:
    #        raise ValidationError('Image is required.')
    #    if not Upload.query.filter_by(filename=field.data).first():
    #        raise ValidationError('Image {filename} not found among uploads.'\
    #                              .format(filename=field.data))

    # def validate_alias(self, field):
    #    if Category.query.filter_by(alias=field.data).first():
    #        raise ValidationError('Category with such alias already exists.')


class CategoryForm(EditCategoryForm):
    def validate_alias(self, field):
        if Category.query.filter_by(alias=field.data).first():
            raise ValidationError('Category with such alias already exists.')


class UploadForm(FlaskForm):
    # https://flask-wtf.readthedocs.org/en/latest/form.html#module-flask_wtf.file
    # https://stackoverflow.com/questions/21155930/flask-wtforms-filefield-not-validating
    image = FileField(
        'Image File',
        validators=[
            FileRequired('File is required.'),
            FileAllowed(['jpg', 'jpeg', 'png', 'gif'], 'Only image files allowed.'),
            file_exists,
        ],
    )
    title = StringField("Title", validators=[DataRequired(), Length(1, 128)])
    submit = SubmitField('Submit')

    # https://wtforms.readthedocs.org/en/latest/validators.html#custom-validators


class NotificationForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(1, 128)])
    body = PageDownField("Text", validators=[DataRequired()])
    group = SelectField('To', coerce=int, default=0)
    email = BooleanField('Send as email')
    submit = SubmitField('Submit')

    def __init__(self, *args, **kwargs):
        super(NotificationForm, self).__init__(*args, **kwargs)
        self.group.choices = [
            (
                group.id,
                "{name} group ({count})".format(
                    name=group.name,
                    count=User.query.filter(User.role_id == group.id).count(),
                ),
            )
            for group in Role.query.order_by(Role.name).all()
        ]
        self.group.choices.append((0, "All users ({0})".format(User.query.count())))


class CsrfTokenForm(FlaskForm):
    """A form used on pages with AJAX POST requests to get access to an CSRF token."""

    id = HiddenField('Entry id', validators=[DataRequired()])

pili/ctrl/__init__.py
from flask import Blueprint

ctrl = Blueprint('ctrl', __name__)

from pili.ctrl import views, errors
from pili.models import Permission


@ctrl.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

pili/ctrl/views.py
import os
from datetime import datetime

from flask import (
    abort,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user, login_required
from flask_sqlalchemy import get_debug_queries
from werkzeug.utils import secure_filename

from pili.app import db
from pili.ctrl import ctrl
from pili.decorators import admin_required, permission_required
from pili.email import send_email
from pili.filters import (
    find_thumbnail,
    get_added_removed,
    sanitize_alias,
    sanitize_tags,
)
from pili.models import (
    Category,
    Comment,
    Message,
    MessageAck,
    Permission,
    Post,
    Role,
    Tag,
    Tagification,
    Upload,
    User,
)

from .forms import (
    CategoryForm,
    CsrfTokenForm,
    EditCategoryForm,
    EditProfileAdminForm,
    EditProfileForm,
    NotificationForm,
    PostForm,
    UploadForm,
)


@ctrl.route('/', methods=['GET', 'POST'])
@login_required
def posts():
    csrf_form = CsrfTokenForm()
    form = PostForm()
    if current_user.can(Permission.WRITE) and form.validate_on_submit():
        # add post
        upload = Upload.query.filter_by(filename=form.image.data).first()
        category = Category.query.filter_by(id=form.category.data).first()
        post = Post(
            title=form.title.data,
            alias=sanitize_alias(form.alias.data),
            timestamp=form.timestamp.data,
            body=form.body.data,
            description=form.description.data,
            author=current_user._get_current_object(),
            image=upload,
            featured=form.featured.data,
            commenting=form.commenting.data,
            category=category,
        )
        db.session.add(post)

        # add tags
        tags = sanitize_tags(form.tags.data)
        if tags:
            tag_aliases = [sanitize_alias(t) for t in tags]
            for t in zip(tags, tag_aliases):
                tag_title = t[0]
                tag_alias = t[1]
                tag = Tag.query.filter(Tag.alias == tag_alias).first()
                # add a single tag if it doesn't exist yet
                if not tag:
                    tag = Tag(title=tag_title, alias=tag_alias)
                    db.session.add(tag)

                # flush session to obtain post.id and tag.id
                db.session.flush()
                tagification = Tagification.query.filter_by(
                    tag_id=tag.id, post_id=post.id
                ).first()
                # add entry to M-to-M posts-tags table
                if not tagification:
                    cl = Tagification(tag_id=tag.id, post_id=post.id)
                    db.session.add(cl)

        flash('Your post has been published.', 'success')
        return redirect(url_for('.posts'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    body_truncate = current_app.config['PILI_BODY_TRUNCATE']
    return render_template(
        'ctrl/posts.html',
        csrf_form=csrf_form,
        form=form,
        posts=posts,
        body_truncate=body_truncate,
        datetimepicker=datetime.utcnow(),
        pagination=pagination,
    )


# TODO: rewrite as API function
@ctrl.route('/remove-post', methods=['POST'])
def remove_post():
    try:
        id = request.json['id']
        csrf = request.json['csrf']  # noqa: F841
    except (KeyError, TypeError):
        return jsonify(
            {
                'status': 'error',
                'message': 'Function takes two parameters: '
                'id of the entry to be removed; csrf token',
            }
        )

    post = Post.query.get_or_404(id)
    # check permissions
    if current_user != post.author and not (
        current_user.has_role('Administrator') or current_user.has_role('Editor')
    ):
        abort(403)
    # remove tags
    # TODO rewrite as 'after_flush' listener, it's much more memory effective
    if post.tags.count():
        tags = post.tags.all()
        for t in tags:
            # remove entries from M2M tagification table
            Tagification.query.filter_by(tag_id=t.id, post_id=post.id).delete(
                synchronize_session='fetch'
            )
            # if the tag is not in use in other post(s), remove it
            in_other_posts = Tagification.query.filter(
                Tagification.tag_id == t.id, Tagification.post_id != post.id
            ).count()
            if not in_other_posts:
                db.session.delete(t)

    # remove comments
    for c in post.comments.all():
        db.session.delete(c)

    status = 'success'
    message = "Post '{0}', associated tags and comments have been removed".format(
        post.title
    )
    db.session.delete(post)
    return jsonify({'status': status, 'message': message})


@ctrl.route('/tag/<alias>')
def tag(alias):
    tag = Tag.query.filter_by(alias=alias).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = tag.posts.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    return render_template('tag.html', tag=tag, pagination=pagination, posts=posts)


@ctrl.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PILI_POSTS_PER_PAGE'], error_out=False
    )
    posts = pagination.items
    return render_template(
        'main/user.html', user=user, posts=posts, pagination=pagination
    )


@ctrl.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.', 'success')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('ctrl/edit_profile.html', form=form)


@ctrl.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        flash('The profile has been updated.', 'success')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('ctrl/edit_profile.html', form=form, user=user)


@ctrl.route('/edit-post/<int:id>/<alias>', methods=['GET', 'POST'])
@login_required
def edit_post(id, alias):
    """Edit an existing post.

    User has to be logged in and be either:
    - Author of the post
    - Editor (role)
    - Administrator (role)
    """
    post = Post.query.get_or_404(id)
    if current_user != post.author and not (
        current_user.has_role('Administrator') or current_user.has_role('Editor')
    ):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        upload = Upload.query.filter_by(filename=form.image.data).first()
        category = Category.query.filter_by(id=form.category.data).first()

        post.title = form.title.data
        post.alias = sanitize_alias(form.alias.data)
        post.timestamp = form.timestamp.data
        post.description = form.description.data
        post.body = form.body.data
        post.image = upload
        post.featured = form.featured.data
        post.commenting = form.commenting.data
        post.category = category

        db.session.add(post)

        # update tags
        new_tags = sanitize_tags(form.tags.data)
        old_tags = sanitize_tags(', '.join([c.title for c in post.tags.all()]))
        added_tag_titles, removed_tag_titles = get_added_removed(new_tags, old_tags)
        # add new tags
        added_tag_aliases = [sanitize_alias(c) for c in added_tag_titles]
        for c in zip(added_tag_titles, added_tag_aliases):
            tag_alias = c[1]
            tag = Tag.query.filter(Tag.alias == tag_alias).first()
            # if tag doesn't exist in the db, add it
            if not tag:
                tag = Tag(title=c[0], alias=c[1])
                db.session.add(tag)

            # add relation between the Post and the Tag
            # flush session to obtain tag.id, if the tag has been added recently
            db.session.flush()

            cl = Tagification(tag_id=tag.id, post_id=id)
            db.session.add(cl)

        # remove obsolete tags
        removed_tag_aliases = [sanitize_alias(c) for c in removed_tag_titles]

        for c in zip(removed_tag_titles, removed_tag_aliases):
            tag_alias = c[1]
            tag = Tag.query.filter(Tag.alias == tag_alias).first()

            # remove relations
            old_cl = Tagification.query.filter(
                Tagification.tag_id == tag.id, Tagification.post_id == id

pili/templates/ctrl/_categories.html
<ul class="ctrl-list">
  {% for category in categories %}
  <li id="category{{ category.id }}" class="ctrl-item">
    <div class="ctrl-item-thumbnail">
      {% if category.image %}
      <img src="{{ category.image.filename | thumbnail('30x30', crop='fit', quality=75) }}"
	   class="img-responsive img-thumbnail"
	   title="{{ category.image.title | e }}" alt="{{ category.image.title | e }}">
      {% else %}
      <span class="glyphicon glyphicon-minus" aria-label="None" title="No Image"></span>
      {% endif %}
    </div>

    <div class="ctrl-item-content">
      <div class="ctrl-item-date">{{ moment(category.timestamp).fromNow() }}</div>
      <strong><a href="{{ url_for('main.category', alias=category.alias) }}">
	  {{ category.title }}
      </a></strong>
      by
      <span class="glyphicon glyphicon-user"></span>
      <a href="{{ url_for('main.user', username=category.author.username) }}">
	{{ category.author.username }}
      </a>
      <div class="ctrl-item-body">
	<p>
	  <strong>Alias:</strong> {{ category.alias }}<br>
	  {% if category.description %}
	  <strong>Description:</strong> {{ category.description | truncate(**body_truncate) }}<br>
	  {% endif %}	  
	  <strong>Body:</strong>  {{ category.body | truncate(**body_truncate) }}<br>
          <strong>Featured: </strong> {% if category.featured %}[x]
	  {% else %}[ ]{% endif %}<br>
	  <strong>Posts:</strong>  {{ category.posts.count() }}<br>
	</p>

	{% if current_user.can(Permission.STRUCTURE) %}
	<a class="btn btn-xs btn-primary" href="{{ url_for('ctrl.edit_category', id=category.id, alias=category.alias) }}" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
	{% endif %}
	{% if current_user.has_role('Administrator') %}
	<button class="btn btn-xs btn-danger remove" type="button" title="Remove" data-action="remove" data-id-removal="{{ category.id }}"><span class="glyphicon glyphicon-remove"></span></button>
	{% endif %}
      </div>
    </div>
  </li>
  {% endfor %}
</ul>

pili/templates/ctrl/_posts.html
<ul class="ctrl-list">
  {% for post in posts %}
  <li id="post{{ post.id }}" class="ctrl-item">
    <div class="ctrl-item-thumbnail">
      {% if post.image %}
      <img src="{{ post.image.filename | thumbnail('30x30', crop='fit', quality=75) }}"
	   class="img-responsive img-thumbnail"
	   title="{{ post.image.title | e }}" alt="{{ post.image.title | e }}">
      {% else %}
      <span class="glyphicon glyphicon-minus" aria-label="None" title="No Image"></span>
      {% endif %}
    </div>

    <div class="ctrl-item-content">
      <div class="ctrl-item-date">{{ moment(post.timestamp).fromNow() }}</div>
      <strong><a href="{{ url_for('main.post', category=post.category.alias, id=post.id, alias=post.alias) }}">
	  {{ post.title }}
      </a></strong>
      by
      <span class="glyphicon glyphicon-user"></span>
      <a href="{{ url_for('main.user', username=post.author.username) }}">
	{{ post.author.username }}
      </a>
      <div class="ctrl-item-body">
	<p>
	  <strong>Alias:</strong> {{ post.alias }}<br>
	  {% if post.description %}
	  <strong>Description:</strong> {{ post.description | truncate(**body_truncate) }}<br>
	  {% endif %}
	  <strong>Body:</strong>  {{ post.body | truncate(**body_truncate) }}<br>
          <strong>Featured: </strong> {% if post.featured %}[x]
	  {% else %}[ ]{% endif %}<br>
	  <strong>Commenting: </strong> {% if post.commenting %}[x]
	  {% else %}[ ]{% endif %}<br>
	  {% if post.comments.count() %}
	  <strong>Comments: </strong> {{ post.comments.count() }}
	  {% endif %}

	</p>

	{% if current_user == post.author or
	current_user.has_role('Administrator') or 
	current_user.has_role('Editor')  %}
	<a class="btn btn-xs btn-primary" href="{{ url_for('ctrl.edit_post', id=post.id, alias=post.alias) }}" title="Edit"><span class="glyphicon glyphicon-pencil"></span></a>
	<button class="btn btn-xs btn-danger remove" type="button" title="Remove" data-action="remove" data-id-removal="{{ post.id }}"><span class="glyphicon glyphicon-remove"></span></button>
	{% endif %}
      </div>
    </div>
  </li>
  {% endfor %}
</ul>

pili/templates/ctrl/_uploads.html
<ul class="ctrl-list">
  {% for image in images %}
  <li id="image{{ image.id }}" class="ctrl-item">
    <div class="ctrl-item-thumbnail">
      <img src="{{ image.filename | thumbnail('30x30', crop='fit', quality=75) }}"
	   class="img-responsive img-thumbnail"
	   title="{{ image.title | e }}" alt="{{ image.title | e }}">
    </div>
    
    <div class="ctrl-item-content">
      <div class="ctrl-item-date">{{ moment(image.timestamp).fromNow() }}</div>
      <strong>{{ image.filename }}</strong>
      by
      <span class="glyphicon glyphicon-user"></span>
      <a href="{{ url_for('main.user', username=image.owner.username) }}">
	{{ image.owner.username }}
      </a>
      <div class="ctrl-item-body">
	<p>
	  <strong>Filename:</strong> {{ image.filename }}<br>
	  {% if image.title %}
	  <strong>Title:</strong> {{ image.title | e }}<br>
	  {% endif %}
	  <strong>Absolute Path:</strong><br>
	  {% set path = url_for('static', filename='uploads/', _external=True) + image.filename %}
	  <textarea rows="1" cols="{{ path | length }}" class="copy-path">{{ path }}</textarea>
	</p>

	{#<a class="btn btn-xs btn-default" href="{{ url_for('.view_upload', filename=image.filename) }}" title="View Image"><span class="glyphicon glyphicon-eye-open"></span></a>#}
	<a class="btn btn-xs btn-default" href="{{ path }}" target="_blank" title="View Image"><span class="glyphicon glyphicon-eye-open"></span></a>
	{% if current_user.can(Permission.UPLOAD) %}
	<button class="btn btn-xs btn-danger remove" type="button" title="Remove" data-action="remove" data-filename-removal="{{ image.filename }}"><span class="glyphicon glyphicon-remove"></span></button>
	{% endif %}
      </div>
    </div>
  </li>
  {% endfor %}
</ul>

pili/templates/ctrl/_users.html
<ul class="ctrl-list">
    {% for user in users %}
    <li id="user{{ user.id }}" class="ctrl-item">
      <div class="ctrl-item-thumbnail">
	{% if user.confirmed %}
        <a href="{{ url_for('main.user', username=user.username) }}">
          <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=40) }}">
        </a>
	{% else %}
	<span class="glyphicon glyphicon-minus"></span>
	{% endif %}
        </div>

        <div class="ctrl-item-content">
            <div class="ctrl-item-date">{{ moment(user.member_since).fromNow() }}</div>
            <div class="ctrl-item-author">
	       {% if user.confirmed %}
	       <a href="{{ url_for('.user', username=user.username) }}">
		 {{ user.username }}
	       </a> {% if user.name %}({{ user.name}}){% endif %}
	       {% else %}
	       None <span class="label label-danger">not confirmed</span>
	       {% endif %}
	    </div>
	    
            <div class="ctrl-item-body">
	      <p>
		Role: {{ user.role.name }}
		[<code title="a: administer, s: structure, m: moderate, u: upload, c: comment, w: write, f: follow, r: read">{{ user.role.permissions | permissions2str }}</code>] <br>
		{% if current_user.is_administrator() and not user.confirmed %}
		Email: {{ user.email }}
		{% endif %}
		{% if user.confirmed %}
		Posts written: <a href="{{ url_for('main.user', username=user.username, _anchor='posts') }}">{{ user.posts.count() }}</a> |
		Categories created: {{ user.categories.count() }} |
		Files uploaded: {{ user.images.count() }} |
		Comments written: <a href="{{ url_for('main.comments', username=user.username) }}">{{ user.comments.count() }}</a> |
		Replies received: <a href="{{ url_for('main.replies', username=user.username) }}">{{ user.replies.count() }}</a>
		{% endif %}
	      </p>

	      {% if current_user.is_administrator() %}
              <a class="btn btn-xs btn-default" href="{{ url_for('ctrl.edit_profile_admin', id=user.id) }}"><span class="glyphicon glyphicon-pencil" aria-label="EditProfileAdmin" title="Edit profile [Admin]"></span></a>
              {% endif %}
              {% if current_user != user %}
	      {% if user.role.name != 'Suspended' %}
	      <button class="btn btn-primary btn-xs remove" type="button" title="Suspend user" data-action="suspend" data-id-removal="{{ user.id }}"><span class="glyphicon glyphicon-off" aria-label="Suspend"></span></button>
	      {% endif %}
	      <button class="btn btn-danger btn-xs remove" type="button" title="Remove user with all posts and comments" data-action="remove" data-id-removal="{{ user.id }}"><span class="glyphicon glyphicon-trash" aria-label="Remove"></span></button>
	      {% endif %}

        </div>
    </li>
    {% endfor %}
</ul>

pili/templates/ctrl/base.html
{% extends "main/base.html" %}

{% block title %}Control Panel {{ super() }}{% endblock %}
{% block head %}{{ super() }}{% endblock %}

{% block navbar %}{{ super() }}{% endblock %}

{% block navbar_left_items %}
{% if current_user.can(Permission.WRITE) %}
<li {% if page == 'posts' %}class="active"{% endif %}><a href="{{ url_for('ctrl.posts') }}">Posts</a></li>
{% endif %}

{% if current_user.can(Permission.STRUCTURE) %}
<li {% if page == 'categories' %}class="active"{% endif %}><a href="{{ url_for('ctrl.categories') }}">Categories</a></li>
{% endif %}

{% if current_user.can(Permission.MODERATE) %}
<li {% if page == 'comments' %}class="active"{% endif %}><a href="{{ url_for('ctrl.comments') }}">Comments</a></li>
{% endif %}

{% if current_user.can(Permission.UPLOAD) %}	    
<li {% if page == 'uploads' %}class="active"{% endif %}><a href="{{ url_for('ctrl.uploads') }}">Uploads</a></li>
{% endif %}

{% if current_user.can(Permission.ADMINISTER) %}
<li {% if page == 'users' %}class="active"{% endif %}><a href="{{ url_for('ctrl.users') }}">Users</a></li>
<li {% if page == 'invite' %}class="active"{% endif %}><a href="{{ url_for('auth.invite_request') }}">Invite</a></li>
<li {% if page == 'notify' %}class="active"{% endif %}><a href="{{ url_for('ctrl.notify') }}">Notify</a></li>
{% endif %}
{% endblock %}

{% block content %}{{ super() }}{% endblock %}

{% block page_content %}{{ super() }}{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='js/bootstrap-datetimepicker.js') }}"></script>
{% endblock %}

pili/templates/ctrl/edit_profile.html
{% extends "ctrl/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Profile - {{ super() }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

pili/templates/ctrl/moderate.html
{% extends "main/base.html" %}
{% import "main/_macros.html" as macros %}

{% block title %}Comment Moderation{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% set expand = True %}
{% set reply = True %}
{% include 'ctrl/_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'ctrl.moderate') }}
</div>
{% endif %}
{% endblock %}

pili/templates/ctrl/notification.html
{##}

pili/templates/ctrl/notify.html
{% set page = 'notify' %}
{% extends "ctrl/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "ctrl/_macros.html" as macros %}

{% block title %}Send a Message to users {{ super() }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Send Message</h1>
</div>

<div>
  {{ wtf.quick_form(form) }}
</div>

<div class="page-header">
    <h1>List of Messages</h1>
</div>

<div>
  {% include 'ctrl/_messages.html' %}
</div>
  
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'ctrl.notify') }}
</div>
{% endif %}

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}